zone: "JonBedroom"
sonosGateway: "http://localhost:5005/"
deviceName: "Satechi Media Button Consumer Control"

debug: true
refreshConfig: 30

connected:
  - "pause"
  - "play"

bindings:
  115: 
    - path: 
      - "volume/+2"

  114: 
    - path: 
      - "volume/-2"

  163: 
    - path: 
      - "next"

  165: 
    - path: 
      - "previous"

  164: 
    - path: 
      - "playpause"

